### ISSUE TITLE
Initialise Airship sdk at runtime with secret keys from remote source.

### ISSUE THREAD

**Issue by ailic88** [urbanairship/airship-flutter#115]
Is it possible to fetch "productionAppKey" "productionAppSecret" from remote source at runtime and do initialisation?
Or this data has to be part of "airshipconfig.properties" and "AirshipConfig.plist" files respectively for Android and iOS?

### What Airship dependencies are you using?
4.4.0

### What unexpected behavior are you seeing?
 There are no methods exposed for set configuration at runtime

**Comment by rlepinski** [comment]
Its not possible right now in the plugin, but I will look into what it would take to make it possible. In our cordova plugin we make it possible to call takeOff from the cordova context, we then persist those config values. If takeOff is called again, the config wont take effect until next run. I assume that would work for you?

**Comment by ailic88** [comment]
@rlepinski first thanks for quick response. When you say next run, do you mean on cold start("kill" app and run it again) or you mean on warm start(restart and re-initialise). For my app is not acceptable to keep keys locally, so if you could expose takeOff() method it would be perfect. Do you have any ETA when you can apply this change?

**Comment by rlepinski** [comment]
Either, as long as the app has to start the lifecycle again (Android Application#onCreate, iOS didFinishLaunching). The underlying Airship SDK only supports being initialized once per app lifecycle at the moment. And once takeOff is called, we need to reinitialize the SDK during the beginning of the apps lifecycle in order to properly handle notifications. 

If you are just avoiding hardcoding credentials in your app, I don't see any problems with this approach. If you are trying to change what Airship app you point to at runtime, thats where things don't work out as nicely.

In terms of an ETA, I can't really provide that right now. I might have some time to try to get it to work this week but it's not trivial what needs to be done. Ill keep you updated.

**Comment by ailic88** [comment]
@rlepinski this works for me. You can close this issue when new version with the changes is released. Any idea when it could happen?

**Comment by rlepinski** [comment]
Working on wrapping up the release. Hopefully we will have something this week.

**Comment by rlepinski** [comment]
Fixed in 5.3.0
